<template>
  <div class="p-8 bg-bg/[0.03] rounded-[20px] my-5">
    <p class="text-txt text-sm font-[500]">Multi Factor authentication</p>

    <div v-if="step == 1" class="flex items-center gap-6 my-4 text-txt">
        <ui-icon name="auth1" />    
        <div class="flex flex-col gap-3">
            <p>You will need an authenticator mobile app to complete this process such as one of the following</p>
            <div class="font-[500] text-txt flex gap-6 bg-bg/[0.05] p-3 px-6 rounded-[25px] w-fit">
                <div class="flex gap-3 items-center">
                    <ui-icon name="googleAuth" />
                    <p>Google Authenticator</p>
                </div>
                <div class="flex gap-3 items-center">
                    <ui-icon name="microsoftAuth" />
                    <p>Microsoft Authenticator</p>
                </div>
            </div>
        </div>
    </div>

    <div v-if="step == 2" class="flex items-center gap-6 my-4 text-txt">
        <qrcode class="rounded-[20px]" :value="qrtext" :size="50" :margin="8" :color="{ dark: '#fff', light: '#D9D9D908' }" />
        <div class="flex flex-col gap-3">
            <p class="">Scan the QR code with your authenticator</p>
            <p class="text-sm text-txt/50">If you can’t scan the code, you can enter this secret key into your authentication app </p>
            <div class="rounded-[10px] flex items-center justify-between p-4 border border-txt/30">
                <p v-if="secret" class="uppercase">{{secret.replace(/(.{4})/g, '$1 ').trim()}}</p>
                <ui-icon name="clip" class="cursor-pointer" @click="copyToClipboard" />
            </div>
            <p v-if="copySuccess" class="text-sm text-txt/50">Text copied to clipboard!</p>
        </div>
    </div>

    <div v-if="step == 3" class="flex items-center gap-6 my-4 text-txt">
        <ui-icon name="auth3" />    
        <div class="flex flex-col gap-3">
            <p class="">After scanning the QR code above, enter the six-digit code generated by your authenticator</p>
            <div class="flex gap-3 items-center w-[369px]">
                <div class="" v-for="i in 3" :key="i">
                    <ui-ipt 
                    @input="onInput(i, $event)"
                    ref="inputs"
                    :maxlength="'1'"
                    v-model="code[i]"
                    :cclass="'text-center pl-0 w-[50px] h-[50px] '"
                    class="bg-[unset] border border-txt/20"/>
                </div>
                <div>-</div>
                <div class="" v-for="i in 3" :key="i">
                    <ui-ipt 
                    @input="onInput(i + 3, $event)"
                    ref="inputs"
                    :maxlength="'1'"
                    v-model="code[i + 3]"
                    :cclass="'text-center pl-0 w-[50px] h-[50px]'"
                    class=" bg-[unset] border border-txt/20"/>
                </div>
            </div>
        </div>
    </div>

    <div v-if="step == 4" class="flex items-center gap-6 my-4 text-txt">
        <ui-icon name="auth4" />    
        <div class="flex flex-col gap-3">
            <p class="">You’re all set</p>
            <p class="text-sm text-txt/50">now you can use the mobile authentication app to get an authentication code any time you log in to Antercept</p>
        </div>
    </div>

    <div v-if="step == 5" class="flex items-center gap-6 my-4 text-txt">
        <ui-icon name="auth4" />    
        <div class="flex flex-col gap-3">
            <p class="">2FA is active</p>
        </div>
    </div>

    <div v-if="step < 4" class="flex gap-4 justify-end items-center">
        <p class="text-acc/90 text-lg">{{message}}</p>
        <ui-btn  @click="nextStep" text="next" :mode="'main'" class="mr-6" />
    </div>

    <div v-if="step == 4" class="flex justify-end">
        <ui-btn  @click="disable2FA" text="deactivate 2FA" class="mr-6" />
        <ui-btn  @click="step = 1" text="reset" :mode="'normal'" class="mr-6" />
        <ui-btn  @click="step = 5" text="Finish" :mode="'main'" class="mr-6" />
    </div>

    <div v-if="step == 5" class="flex justify-end">
        <ui-btn  @click="disable2FA" text="deactivate 2FA" class="mr-6" />
    </div>

  </div>
</template>

<script>
import { mapGetters } from 'vuex';

import Qrcode from 'vue-qrcode';

export default {
    components: {Qrcode},  
    data() {
        return{
            step: 1,
            qrtext: '',
            secret: '',
            code: [],
            message: '',
            copySuccess: false
        }
    },
    computed: {
      ...mapGetters(['getUser']),
      user() {
        return this.getUser; 
      },
    },
    mounted() {
        if(this.user.twoFA) {
            this.step = 5
        }
    },
    methods: {
        async nextStep() {
            let r = true
            if(this.step == 1) await this.fetchQRCode()
            if(this.step == 3) {
                r = await this.verifyCode()

            }
            if(this.step == 3 && r) {
                await this.refreshUser()
                this.code = []
            }
            if(r) this.step++
        },
        async fetchQRCode() {
            try {
                const response = await this.$axios.get('/get-qrcode')
                this.qrtext = response.data.qr_code;
                this.secret = response.data.secret;
            } catch (error) {
                console.error('Error fetching QR code:', error);
            }
        },
        async verifyCode() {
            try {
                const response = await this.$axios.post('/verify-totp', { code: this.code.join('') })

                return true
            } catch (error) {
                this.message = error.response?.data?.message || 'Verification failed';
                return false
            }
        },
        onInput(index, event) {
            const value = event.target.value;
            if (value.length === 1) {
                const nextInput = this.$refs.inputs[index];
                if (nextInput) {
                    console.log(nextInput);
                    nextInput.focus();
                }
            }
        },
        async copyToClipboard() {
            try {
                await navigator.clipboard.writeText(this.secret);
                    this.copySuccess = true;
                setTimeout(() => {
                    this.copySuccess = false;
                }, 2000);
            } catch (err) {
                console.error('Failed to copy: ', err);
            }
        },
        async disable2FA() {
            await this.$axios.get('/disable2FA')
                .then(r => {
                    console.log(r);
                })
            await this.refreshUser()
            this.step = 1
        },
        async refreshUser() {
            await this.$axios.get('/getuser')
                .then(r => {
                    this.$store.dispatch('updateUser', {...r.data, token: this.user.token}); 
                })  
        }
    }
}
</script>
<style scoped>
.qr-container {
  display: flex;
  flex-direction: column;
  align-items: center;
  margin: 20px;
  padding: 20px;
  border: 2px solid #4CAF50; /* Change border color */
  border-radius: 10px; /* Rounded corners */
  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2); /* Box shadow for depth */
  background-color: #f9f9f9; /* Light background */
}

.qr-title {
  font-size: 24px;
  margin-bottom: 10px;
  color: #333; /* Dark text color */
}

.qr-input {
  width: 100%;
  max-width: 300px; /* Set max width for input */
  padding: 10px;
  margin-bottom: 20px;
  border: 1px solid #ccc; /* Border for input */
  border-radius: 5px; /* Rounded corners */
  transition: border-color 0.3s; /* Smooth transition for focus effect */
}

.qr-input:focus {
  outline: none; /* Remove default outline */
  border-color: #4CAF50; /* Change border color on focus */
}

.qr-code {
  margin-top: 20px; /* Space above the QR code */
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 10px;
  background-color: #ffffff; /* White background for QR code */
  border-radius: 10px; /* Rounded corners */
  box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1); /* Subtle shadow */
}
</style>